module.exports = {
    Netflix: /(?=USER-AGENT,Argo\*,|DOMAIN-SUFFIX,netflix.com,|DOMAIN-SUFFIX,netflix.net,|DOMAIN-SUFFIX,nflxext.com,|DOMAIN-SUFFIX,nflximg.com,|DOMAIN-SUFFIX,nflximg.net,|DOMAIN-SUFFIX,nflxvideo.net,|IP-CIDR,23.246.0.0\/12,|IP-CIDR,37.77.0.0\/12,|IP-CIDR,45.57.0.0\/12,|IP-CIDR,64.120.128.0\/17,|IP-CIDR,66.197.128.0\/17,|IP-CIDR,108.175.0.0\/12,|IP-CIDR,185.2.0.0\/12,|IP-CIDR,185.9.188.0\/22,|IP-CIDR,192.173.64.0\/18,|IP-CIDR,198.38.0.0\/12,|IP-CIDR,198.45.0.0\/12,)[^\n]+/g,
    Spotify: /(?=PROCESS-NAME,Spotify,|DOMAIN-SUFFIX,spoti.fi,|DOMAIN-KEYWORD,spotify,|USER-AGENT,\*Spotify\*,|DOMAIN-SUFFIX,scdn.co,|DOMAIN-SUFFIX,spotify.com,)[^\n]+/g,
    YouTube: /(?=USER-AGENT,com.google.ios.youtube\*,|USER-AGENT,YouTube\*,|DOMAIN-SUFFIX,googlevideo.com,|DOMAIN-SUFFIX,youtube.com,|DOMAIN-KEYWORD,youtube,)[^\n]+/g,
    MytvSUPER: /(?=DOMAIN-KEYWORD,nowtv100,|DOMAIN-KEYWORD,rthklive,|DOMAIN-SUFFIX,mytvsuper.com,|DOMAIN-SUFFIX,tvb.com,)[^\n]+/g,
    BBC: /(?=USER-AGENT,BBCiPlayer\*,|USER-AGENT,BBCBeacon\*,|DOMAIN-KEYWORD,co.uk,|DOMAIN-KEYWORD,uk-live,|DOMAIN-SUFFIX,bbc.co,|DOMAIN-SUFFIX,bbc.com,|DOMAIN-SUFFIX,bbci.co.uk,|DOMAIN-SUFFIX,bbc.co.uk,|DOMAIN-SUFFIX,vod-hls-uk-live.akamaized.net,)[^\n]+/g,
    LINE: /(?=DOMAIN-SUFFIX,lin.ee,|DOMAIN-SUFFIX,line.me,|DOMAIN-SUFFIX,line.naver.jp,|DOMAIN-SUFFIX,line-apps.com,|DOMAIN-SUFFIX,line-cdn.net,|DOMAIN-SUFFIX,line-scdn.net,|DOMAIN-SUFFIX,nhncorp.jp,|IP-CIDR,103.2.28.0\/22,|IP-CIDR,119.235.224.0\/21,|IP-CIDR,119.235.232.0\/23,|IP-CIDR,119.235.235.0\/24,|IP-CIDR,119.235.236.0\/23,|IP-CIDR,125.6.146.0\/24,|IP-CIDR,125.6.149.0\/24,|IP-CIDR,125.6.190.0\/24,|IP-CIDR,125.209.208.0\/20,|IP-CIDR,203.104.103.0\/24,|IP-CIDR,203.104.128.0\/20,|IP-CIDR,203.174.66.64\/26,|IP-CIDR,203.174.77.0\/24,)[^\n]+/g,
    SoundCloud: /(?=USER-AGENT,SoundCloud\*,|DOMAIN-SUFFIX,soundcloud.com,|DOMAIN-SUFFIX,sndcdn.com,)[^\n]+/g,
    Google: /(?=DOMAIN-SUFFIX,goo.gl,|DOMAIN-SUFFIX,gvt1.com,|DOMAIN-SUFFIX,youtu.be,|DOMAIN-SUFFIX,ytimg.com,|DOMAIN-SUFFIX,ggpht.com,|DOMAIN-KEYWORD,gmail,|DOMAIN-KEYWORD,google,|DOMAIN-KEYWORD,gstatic,|DOMAIN-KEYWORD,youtube,|USER-AGENT,WalletAPP.app\*,|USER-AGENT,Wallet\*iSL\*,|DOMAIN-SUFFIX,google.com,|DOMAIN-SUFFIX,googleapis.com,)[^\n]+/g,
    PayPal: /(?=USER-AGENT,PayPal\*,|DOMAIN-KEYWORD,paypal,|DOMAIN-SUFFIX,paypal.com,)[^\n]+/g,
    Microsoft: /(?=USER-AGENT,Microsoft\*,|USER-AGENT,OneDrive\*,|DOMAIN-KEYWORD,microsoft,|DOMAIN-SUFFIX,bing.com,|DOMAIN-SUFFIX,bing.net,|DOMAIN-SUFFIX,cloudappsecurity.com,|DOMAIN-SUFFIX,docs.com,|DOMAIN-SUFFIX,hotmail.com,|DOMAIN-SUFFIX,live.com,|DOMAIN-SUFFIX,live.net,|DOMAIN-SUFFIX,microsoft.com,|DOMAIN-SUFFIX,msedge.net,|DOMAIN-SUFFIX,msn.com,|DOMAIN-SUFFIX,office.com,|DOMAIN-SUFFIX,office.net,|DOMAIN-SUFFIX,office365.com,|DOMAIN-SUFFIX,onedrive.com,|DOMAIN-SUFFIX,onenote.com,|DOMAIN-SUFFIX,onenote.net,|DOMAIN-SUFFIX,onmicrosoft.com,|DOMAIN-SUFFIX,outlook.com,|DOMAIN-SUFFIX,outlookgroups.ms,|DOMAIN-SUFFIX,visualstudio.com,|DOMAIN-SUFFIX,windows.com,|DOMAIN-SUFFIX,windows.net,|DOMAIN-SUFFIX,windowsupdate.com,)[^\n]+/g,
    YoutubeMusic: /(?=USER-AGENT,\*youtubemusic\*,|USER-AGENT,YouTubeMusic\*,)[^\n]+/g,
    TVB: /(?=USER-AGENT,mytv\*,|DOMAIN-SUFFIX,mytvsuper.com,|DOMAIN-KEYWORD,nowtv100,|DOMAIN-KEYWORD,rthklive,|DOMAIN-SUFFIX,tvb.com,|USER-AGENT,OTT_iPhone\*,|USER-AGENT,Viu\*,|DOMAIN-SUFFIX,viu.com,)[^\n]+/g,
    Vidol: /(?=USER-AGENT,Vidol\*,|DOMAIN-SUFFIX,vidol.tv,)[^\n]+/g,
    Hulu: /(?=DOMAIN-SUFFIX,hulu.com,)[^\n]+/g
}
